[default]

SQLALCHEMY_TRACK_MODIFICATIONS='False'
SQLALCHEMY_DATABASE_URI='postgresql://postgres:Senha.123@localhost:5432/pnboia'

SECRET_KEY = 'qualquer'

EXTENSIONS = [
    'application.extensions.database',
    'application.extensions.commands',
    'application.extensions.auth',
    'application.extensions.dashboard.dash_boia',

    'application.blueprints.views',


]
