[default]
SQLALCHEMY_DATABASE_URI='sqlite:///database.db'

SECRET_KEY = 'qualquer'

EXTENSIONS = [
    'application.extensions.database',
    'application.extensions.commands',



    'application.blueprints.views',
]
