[default]

SQLALCHEMY_TRACK_MODIFICATIONS='False'
SQLALCHEMY_DATABASE_URI='sqlite:///database.db'

SECRET_KEY = 'qualquer'

EXTENSIONS = [
    'application.extensions.database',
    'application.extensions.commands',
    'application.extensions.dashboard.dash_boia',

    'application.blueprints.views',


]
