BUOYS = [
    'noronha',
    'alcatrazes',
    'mexilhao',
    'bc1',
    'keller',
    'pinguim',
    '_potter',
    'abrolhos',
    'trindade',
    'bmo_santos',
    'antartica',
    'minuano',
    'itaguai',
    'itaoca',
    'niteroi2',
    'fortaleza',
    'vitoria',
    'cabofrio2',
    'niteroi',
    'santos',
    'itajai',
    'riogrande',
    'recife',
    'portoseguro',
    'cabofrio',
]
URL = 'https://www.marinha.mil.br/chm/dados-do-goos-brasil/pnboia-mapa'
FILE_URL = 'https://www.marinha.mil.br/chm/sites/www.marinha.mil.br.chm/files/'
